services:
  - type: web
    name: quantalpha-api
    runtime: python
    rootDir: backend/quantalpha
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn python.engine:app --host 0.0.0.0 --port $PORT

  - type: web
    name: algoforge-api
    runtime: python
    rootDir: backend/algoforge
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn python.pricer:app --host 0.0.0.0 --port $PORT

  - type: web
    name: quant-portfolio-dashboard
    runtime: static
    rootDir: frontend
    staticPublishPath: .