-- ============================================================
-- QuantAlpha: Statistical Arbitrage Platform
-- SQL Schema - Data Cleaning & Analysis Layer
-- ============================================================

-- Raw market data ingestion table
CREATE TABLE IF NOT EXISTS raw_ohlcv (
    id          SERIAL PRIMARY KEY,
    symbol      VARCHAR(10) NOT NULL,
    ts          TIMESTAMPTZ NOT NULL,
    open        NUMERIC(12,4),
    high        NUMERIC(12,4),
    low         NUMERIC(12,4),
    close       NUMERIC(12,4),
    volume      BIGINT,
    source      VARCHAR(30) DEFAULT 'yfinance',
    ingested_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cleaned & adjusted prices (after outlier removal, split adjustment)
CREATE TABLE IF NOT EXISTS prices_clean (
    id           SERIAL PRIMARY KEY,
    symbol       VARCHAR(10) NOT NULL,
    ts           TIMESTAMPTZ NOT NULL,
    close_adj    NUMERIC(12,4) NOT NULL,
    log_return   NUMERIC(16,8),
    is_outlier   BOOLEAN DEFAULT FALSE,
    UNIQUE (symbol, ts)
);

-- Cointegration pairs discovered by analysis
CREATE TABLE IF NOT EXISTS coint_pairs (
    id            SERIAL PRIMARY KEY,
    symbol_a      VARCHAR(10) NOT NULL,
    symbol_b      VARCHAR(10) NOT NULL,
    pvalue        NUMERIC(8,6),
    hedge_ratio   NUMERIC(10,6),
    half_life     NUMERIC(8,2),
    discovered_at TIMESTAMPTZ DEFAULT NOW(),
    is_active     BOOLEAN DEFAULT TRUE
);

-- Trading signals generated by the strategy
CREATE TABLE IF NOT EXISTS signals (
    id            SERIAL PRIMARY KEY,
    pair_id       INT REFERENCES coint_pairs(id),
    ts            TIMESTAMPTZ NOT NULL,
    zscore        NUMERIC(10,6),
    signal        SMALLINT CHECK (signal IN (-1, 0, 1)),  -- -1=short, 0=flat, 1=long
    entry_price_a NUMERIC(12,4),
    entry_price_b NUMERIC(12,4),
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Backtest results
CREATE TABLE IF NOT EXISTS backtest_runs (
    id              SERIAL PRIMARY KEY,
    run_name        VARCHAR(50),
    start_date      DATE,
    end_date        DATE,
    initial_capital NUMERIC(14,2),
    final_equity    NUMERIC(14,2),
    total_return    NUMERIC(8,4),
    sharpe_ratio    NUMERIC(8,4),
    max_drawdown    NUMERIC(8,4),
    num_trades      INT,
    win_rate        NUMERIC(6,4),
    params          JSONB,
    run_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- VIEWS for analysis
-- ============================================================

-- 30-day rolling volatility per symbol
CREATE OR REPLACE VIEW v_rolling_vol AS
SELECT
    symbol,
    ts,
    close_adj,
    log_return,
    STDDEV(log_return) OVER (
        PARTITION BY symbol
        ORDER BY ts
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) * SQRT(252) AS annualized_vol_30d
FROM prices_clean
WHERE is_outlier = FALSE;

-- Latest z-scores for active pairs
CREATE OR REPLACE VIEW v_live_signals AS
SELECT
    cp.symbol_a,
    cp.symbol_b,
    cp.hedge_ratio,
    cp.half_life,
    s.zscore,
    s.signal,
    s.ts,
    CASE
        WHEN ABS(s.zscore) > 2.0 THEN 'TRADE'
        WHEN ABS(s.zscore) > 1.0 THEN 'WATCH'
        ELSE 'FLAT'
    END AS status
FROM coint_pairs cp
JOIN signals s ON s.pair_id = cp.id
WHERE cp.is_active = TRUE
  AND s.ts = (
      SELECT MAX(ts) FROM signals s2 WHERE s2.pair_id = cp.id
  );

-- ============================================================
-- DATA CLEANING PROCEDURES
-- ============================================================

-- Flag price outliers using IQR method
CREATE OR REPLACE FUNCTION flag_outliers(p_symbol VARCHAR, p_window INT DEFAULT 20)
RETURNS INT AS $$
DECLARE
    updated_count INT;
BEGIN
    WITH stats AS (
        SELECT
            id,
            log_return,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY log_return)
                OVER (PARTITION BY symbol ORDER BY ts ROWS BETWEEN p_window PRECEDING AND CURRENT ROW) AS q1,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY log_return)
                OVER (PARTITION BY symbol ORDER BY ts ROWS BETWEEN p_window PRECEDING AND CURRENT ROW) AS q3
        FROM prices_clean
        WHERE symbol = p_symbol
    ),
    iqr_bounds AS (
        SELECT id,
               log_return,
               q1 - 1.5*(q3-q1) AS lower_bound,
               q3 + 1.5*(q3-q1) AS upper_bound
        FROM stats
    )
    UPDATE prices_clean pc
    SET is_outlier = TRUE
    FROM iqr_bounds ib
    WHERE pc.id = ib.id
      AND (pc.log_return < ib.lower_bound OR pc.log_return > ib.upper_bound);

    GET DIAGNOSTICS updated_count = ROW_COUNT;
    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_prices_symbol_ts ON prices_clean(symbol, ts DESC);
CREATE INDEX IF NOT EXISTS idx_signals_pair_ts ON signals(pair_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_raw_symbol_ts ON raw_ohlcv(symbol, ts DESC);
